### ISSUE TITLE
1.0 checklist

### ISSUE THREAD

**Issue by pared** [iterative/dvclive#223]
- [x] #225 
- [x] #272
- [x] #246 
- [x] #273 
- [x] #326
- [x] #332
- [x] #231
- [x] #323
- [x] #340
- [x] https://github.com/iterative/dvclive/issues/238
- [x] Context manager https://github.com/iterative/dvclive/pull/354
- [x] #172 
- [x] #103

Nice to have: https://github.com/iterative/dvclive/issues/223#issuecomment-1285109650

**Comment by dberenbaum** [comment]
>     * [ ]   [integrations: How to manage versions #221](https://github.com/iterative/dvclive/issues/221)
>
>     * [ ]  [`step`: Remove methods in favor of `@property`. #172](https://github.com/iterative/dvclive/issues/172)
> 
>     * [ ]  [Complete examples for ML frameworks #283](https://github.com/iterative/dvclive/issues/283)
> 
>     * [ ]  [Decouple epoch metrics logging and checkpoints #103](https://github.com/iterative/dvclive/issues/103)

Do you think any of these are a priority for 1.0 @daavoo?

**Comment by daavoo** [comment]
Nice to have:

- [ ]  #221 
- [ ] #172
- [ ] #283 
- [ ] #103

**Comment by dberenbaum** [comment]
More nice to have:

- [ ] https://github.com/iterative/dvclive/issues/238
- [ ] https://github.com/iterative/dvclive/issues/310
- [ ] https://github.com/iterative/dvclive/issues/311
- [ ] https://github.com/iterative/dvclive/issues/271
- [ ] https://github.com/iterative/dvclive/issues/224

@daavoo Thoughts on these?

**Comment by dberenbaum** [comment]
@daavoo Should #238 be added to the checklist? I think everything else besides docs is complete.

**Comment by daavoo** [comment]
> @daavoo Should https://github.com/iterative/dvclive/issues/238 be added to the checklist? I think everything else besides docs is complete.

Moved to the top checklist and there is a P.R. #353 
> @daavoo Thoughts on these?

All look like non-breaking changes that can be prioritized but shouldn't block 1.0

**Comment by dberenbaum** [comment]
What about https://github.com/iterative/dvclive/issues/172 and https://github.com/iterative/dvclive/pull/354?
