### ISSUE TITLE
`dvc`: Deprecation of `live` section.

### ISSUE THREAD

**Issue by daavoo** [iterative/dvclive#225]
## Motivation

Having a separate section named `live` can create confusion when introducing DVCLive to users already familiar with `metrics` and `plots`.

Apart from tracking the `metrics` and `plots` generated by DVCLive, the live section is used internally to potentially configure DVCLive (i.e. `summary` ) and generate an HTML report. 

The configuration of the `Live` Python object through `dvc.yaml` results in having 2 ways of doing the same thing and can cause errors among users. Given that there are no internal reasons to configure the `Live` object through `dvc.yaml`, the removal of the `live` section would result in having a single source of truth for configuring DVCLive (the Python code).

Given that `summary` has been removed (#217), if the HTML generation is decoupled from the `dvc.yaml` and instead moved to DVCLive, the `live` section could be replaced with the existing `metrics` and `plots` sections without losing any features.

This would simplify the integration between DVC and DVCLive and reduce the friction for introducing DVCLive to users already familiar `metrics` and `plots`

---

## Implementation

Replace:

```yaml
stages:
  train:
    cmd: python train.py
    deps:
      - train.py
    live:
      training_metrics:
        summary: true
        html: true
```

With:

```yaml
stages:
  train:
    cmd: python train.py
    deps:
      - train.py
    metrics:
      - dvclive.json:
          cache: false
    plots:
      - dvclive/scalars:
          cache: false
      - dvclive/images
```
---

## Tasks

- [x] https://github.com/iterative/dvclive/issues/213
- [x] https://github.com/iterative/dvc/pull/7514
- [x] https://github.com/iterative/dvc/issues/7534
- [x] #229
- [x] #230
- [x] Should close https://github.com/iterative/dvclive/issues/77
