### ISSUE TITLE
2.0 checklist

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvclive#403]
- [x] Always try to save experiment and dvc.yaml by default (with options to disable) (https://github.com/iterative/dvclive/issues/381)
- [x] Don't remove dvc.yaml on init: #440
- [x] Shorten path-separated names in tsv files: #444 
- [x] Stop checking for already logged data (see #431): #445
~- [ ] Default to `save_dvc_exp=True`?~
